<!DOCTYPE html>
<html lang="fr" xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta charset="UTF-8"/>
</head>
<body>
	<p>Bonjour,</p>
	<p>
		Lors de notre dernière distribution de calendriers, vous avez fait un don de ${formattedAmount} et nous vous en remercions.
	</p>
	<p>
		Veuillez trouvez ci-joint le reçu correspondant à votre don.
	</p>
	<p>Pour toute question, n'hésitez pas à nous contacter à l'adresse suivante : ${answerAddress}</p>
	<br/>
	<h4>Merci</h4>
	<hr />
	<footer>Amicale des sapeurs pompiers de La Verrie</footer>
</body>
</html>