ALTER TABLE evoucher ADD COLUMN created_by VARCHAR(128);
UPDATE evoucher SET created_by = 'guillaume';
ALTER TABLE evoucher ALTER created_by SET NOT NULL;

ALTER TABLE evoucher ADD COLUMN last_modified_by VARCHAR(128);
UPDATE evoucher SET last_modified_by = 'guillaume';
ALTER TABLE evoucher ALTER last_modified_by SET NOT NULL;

ALTER TABLE evoucher_event ADD COLUMN created_by VARCHAR(128);
UPDATE evoucher_event SET created_by = 'guillaume';
ALTER TABLE evoucher_event ALTER created_by SET NOT NULL;

ALTER TABLE evoucher_event ADD COLUMN last_modified_by VARCHAR(128);
UPDATE evoucher_event SET last_modified_by = 'guillaume';
ALTER TABLE evoucher_event ALTER last_modified_by SET NOT NULL;

DROP TABLE IF EXISTS document_metadata;
CREATE TABLE document_metadata (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    version BIGINT NOT NULL DEFAULT 1,
	created_date TIMESTAMP NOT NULL,
    created_by VARCHAR(128) NOT NULL,
	last_modified_date TIMESTAMP NOT NULL,
	last_modified_by VARCHAR(128) NOT NULL,
    e_voucher_id BIGINT NOT NULL,
    document_type INTEGER NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_document_metadata__evoucher FOREIGN KEY(e_voucher_id) REFERENCES evoucher(id),
    CONSTRAINT u_document_metadata__e_voucher_id__document_type UNIQUE (e_voucher_id, document_type)
);

CREATE INDEX ix_document_metadata__evoucher ON document_metadata(e_voucher_id);

DROP TABLE IF EXISTS document_content;
CREATE TABLE document_content (
    id BIGINT,
    content BLOB NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_document_content__document_metadata FOREIGN KEY(id) REFERENCES document_metadata(id)
);


