
DROP TABLE IF EXISTS evoucher;
CREATE TABLE evoucher (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	version BIGINT NOT NULL DEFAULT 1,
	created_date TIMESTAMP NOT NULL,
	last_modified_date TIMESTAMP NOT NULL,
	
	donor_type INTEGER NOT NULL CHECK (donor_type>0),
	
	donor_name VARCHAR(255),
	donor_lastname VARCHAR(128),
	donor_firstname VARCHAR(128),
	donor_address VARCHAR(255),
	donor_zipcode VARCHAR(12),
	donor_city VARCHAR(64),
	donor_countrycode VARCHAR(12),
	donor_email VARCHAR(255),
	
	amount NUMERIC(20, 5) NOT NULL CHECK (amount>=0),
	distribution_year INTEGER NOT NULL,
	donation_date TIMESTAMP NOT NULL,
	payment_method INTEGER NOT NULL,
	
	hash_key VARCHAR(64) NOT NULL,
	indexing_strategy INTEGER NOT NULL,
	
	donor_latitude DOUBLE PRECISION,
	donor_longitude DOUBLE PRECISION,
	
	status INTEGER NOT NULL,
	
	PRIMARY KEY (id)
);

DROP TABLE IF EXISTS evoucher_event;
CREATE TABLE evoucher_event (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	version BIGINT NOT NULL DEFAULT 1,
	created_date TIMESTAMP NOT NULL,
	event_type INTEGER NOT NULL,
	evoucher_id BIGINT NOT NULL,
	PRIMARY KEY (id),
	CONSTRAINT fk_evoucher_event__evoucher FOREIGN KEY(evoucher_id) REFERENCES evoucher(id)
);

CREATE INDEX ix_evoucher_event__evoucher ON evoucher_event(evoucher_id);


